package rpg.bark

/**
 * Every bark in the game is a stable enum key. The Questbook reacts to these
 * keys -- never to audio analysis (see docs/GAME_CONCEPT_LOCK.md).
 *
 * The full set mirrors the Bark Table in docs/BARK_TRIGGER_TABLE.md.
 */
enum class BarkEvent {
    // ─── Nib -- thief/rogue, greed and escape ────────────────────────────
    NIB_SMELL_TREASURE,
    NIB_SMELL_SEWAGE,
    NIB_IT_WASNT_ME,
    NIB_SHORTCUT,
    NIB_POCKET_CHECK,
    NIB_INNOCENT_WHISTLE,
    NIB_TREASURE_FOUND,

    // ─── Brugg -- warrior, combat-obligation and duty ────────────────────
    BRUGG_ATTACK,
    BRUGG_FALL_BACK,
    BRUGG_THAT_WASNT_SO_BAD,
    BRUGG_WHAT_ARE_YOUR_ORDERS,
    BRUGG_HUNGRY,
    BRUGG_PROTECT,
    BRUGG_SMASH,

    // ─── Vellum -- mage, knowledge and elemental contracts ───────────────
    VELLUM_CALLS_FOR_FLAME,
    VELLUM_CALLS_FOR_ICE,
    VELLUM_KNOWLEDGE_IS_THE_ANSWER,
    VELLUM_THIS_CHANGES_EVERYTHING,
    VELLUM_TECHNICALLY_CORRECT,
    VELLUM_READ_THE_FINE_PRINT,

    // ═══ Combat Taunts ═══════════════════════════════════════════════════
    NIB_IS_THAT_ALL_YOUVE_GOT,
    NIB_YOUR_DEFENSES_ARE_WEAK,
    NIB_FROM_THE_SHADOWS,
    BRUGG_HAVE_AT_THEE,
    BRUGG_SURRENDER_OR_DIE,
    BRUGG_SHOW_YOURSELVES,
    VELLUM_LETS_SEE_IF_YOU_CAN_DODGE,
    VELLUM_YOUR_DEFENSES_ARE_FUTILE,
    VELLUM_I_SMITE_YOU,

    // ═══ Combat Reactions (damage/dying) ═════════════════════════════════
    NIB_THAT_STINGS,
    NIB_LUCKY_HIT,
    NIB_AVENGE_ME,
    BRUGG_THATS_GOING_TO_LEAVE_A_MARK,
    BRUGG_I_DONT_HAVE_MUCH_LEFT,
    BRUGG_THAT_DREW_BLOOD,
    VELLUM_IM_GOING_TO_FEEL_THAT,
    VELLUM_I_NEED_A_HEALER,
    VELLUM_I_DIDNT_THINK_IT_WOULD_END,

    // ═══ Combat Reactions (healing/recovery) ═════════════════════════════
    NIB_GOOD_AS_NEW,
    BRUGG_I_FEEL_BETTER_THAN_EVER,
    VELLUM_IM_BACK_ON_MY_FEET,

    // ═══ Exploration / Discovery ═════════════════════════════════════════
    NIB_ITS_A_TRAP,
    NIB_THEYRE_ONTO_US,
    NIB_WHAT_DO_WE_HAVE_HERE,
    BRUGG_THE_DEEPER_WE_GO,
    BRUGG_THIS_LOOKS_LIKE_TROUBLE,
    BRUGG_SURPRISE_SURPRISE,
    VELLUM_TREES_HAVE_EYES,
    VELLUM_HMM_WONDER_WHAT_THIS_IS,
    VELLUM_THIS_LOOKS_LIKE_A_GLYPH,

    // ═══ Ambient / Idle ══════════════════════════════════════════════════
    NIB_I_LOVE_GOLD,
    NIB_THERES_A_HOLE_IN_MY_BOOT,
    NIB_STEW_AGAIN,
    BRUGG_BARKEEP_A_FLAGON,
    BRUGG_GRAB_YOUR_TORCH,
    BRUGG_WHERE_DID_I_PUT_THAT_MAP,
    VELLUM_NOW_WHAT_WAS_THAT_INCANTATION,
    VELLUM_OF_ALL_THE_ARCANE_LORE,
    VELLUM_TIME_WAITS_FOR_NO_MAN,

    // ═══ NPC Dialogue ════════════════════════════════════════════════════
    BARKEEP_SPEND_SOME_COIN,
    BARKEEP_BEEN_PLAYING_IN_SEWERS,
    PATRON_HE_SURE_IS_SLOW,

    // ═══ Extended Combat Taunts ══════════════════════════════════════════
    NIB_BACK_FOUL_CREATURE,
    BRUGG_BACK_FOUL_CREATURE,
    VELLUM_BACK_FOUL_CREATURE,
    NIB_DARKNESS_TAKE_YOU,
    BRUGG_DARKNESS_TAKE_YOU,
    VELLUM_DARKNESS_TAKE_YOU,
    NIB_DROP_YOUR_WEAPONS,
    BRUGG_DROP_YOUR_WEAPONS,
    VELLUM_DROP_YOUR_WEAPONS,
    NIB_YOU_FIGHT_LIKE_A_NEWBORN,
    BRUGG_YOU_FIGHT_LIKE_A_NEWBORN,
    VELLUM_YOU_FIGHT_LIKE_A_NEWBORN,
    NIB_YOU_FIGHT_LIKE_AN_INFANT,
    BRUGG_YOU_FIGHT_LIKE_AN_INFANT,
    VELLUM_YOU_FIGHT_LIKE_AN_INFANT,
    NIB_YOU_FIGHT_LIKE_YOUR_MOTHER,
    BRUGG_YOU_FIGHT_LIKE_YOUR_MOTHER,
    VELLUM_YOU_FIGHT_LIKE_YOUR_MOTHER,
    NIB_MY_NEXT_STRIKE_WILL_FELL_YOU,
    BRUGG_MY_NEXT_STRIKE_WILL_FELL_YOU,
    VELLUM_MY_NEXT_STRIKE_WILL_FELL_YOU,
    NIB_IVE_FOUGHT_KOBOLDS_TOUGHER,
    BRUGG_IVE_FOUGHT_KOBOLDS_TOUGHER,
    VELLUM_IVE_FOUGHT_KOBOLDS_TOUGHER,
    NIB_IVE_FOUGHT_PUPPIES_TOUGHER,
    BRUGG_IVE_FOUGHT_PUPPIES_TOUGHER,
    VELLUM_IVE_FOUGHT_PUPPIES_TOUGHER,
    NIB_IVE_FOUGHT_ARTICHOKES_TOUGHER,
    BRUGG_IVE_FOUGHT_ARTICHOKES_TOUGHER,
    VELLUM_IVE_FOUGHT_ARTICHOKES_TOUGHER,

    // ═══ Victory Barks ═══════════════════════════════════════════════════
    NIB_YOULL_NOT_BE_GETTING_UP,
    BRUGG_YOULL_NOT_BE_GETTING_UP,
    VELLUM_YOULL_NOT_BE_GETTING_UP,
    NIB_NEXT_TIME_WONT_BE_SO_LUCKY,
    BRUGG_NEXT_TIME_WONT_BE_SO_LUCKY,
    VELLUM_NEXT_TIME_WONT_BE_SO_LUCKY,

    // ═══ Damage Reaction ═════════════════════════════════════════════════
    NIB_HOW_HUMILIATING,
    BRUGG_HOW_HUMILIATING,
    VELLUM_HOW_HUMILIATING,

    // ═══ Loot / Container ════════════════════════════════════════════════
    NIB_OOO_ANOTHER_BARREL,
    BRUGG_OOO_ANOTHER_BARREL,
    NIB_YESSS_ANOTHER_CRATE,
    BRUGG_YESSS_ANOTHER_CRATE,
    NIB_I_WONDER_WHATS_IN_THIS_ONE,
    BRUGG_I_WONDER_WHATS_IN_THIS_ONE,
    VELLUM_I_WONDER_WHATS_IN_THIS_ONE,
    NIB_THIS_CHEST_UNLOCKED,
    VELLUM_THIS_CHEST_UNLOCKED,
    NIB_THIS_LOOKS_LIKE_TREASURE,
    BRUGG_THIS_LOOKS_LIKE_TREASURE,
    VELLUM_THIS_LOOKS_LIKE_TREASURE,
    NIB_NOTHING_HERE,
    BRUGG_NOTHING_HERE,
    VELLUM_NOTHING_HERE,
    NIB_IF_IT_GLOWS_MORE_EXPENSIVE,
    BRUGG_IF_IT_GLOWS_MORE_EXPENSIVE,
    VELLUM_IF_IT_GLOWS_MORE_EXPENSIVE,
    NIB_WHY_DO_THEY_LEAVE_LOOT,
    BRUGG_WHY_DO_THEY_LEAVE_LOOT,
    VELLUM_WHY_DO_THEY_LEAVE_LOOT,

    // ═══ Exploration / Navigation ════════════════════════════════════════
    NIB_LETS_GET_OUT_OF_HERE,
    BRUGG_LETS_GET_OUT_OF_HERE,
    VELLUM_LETS_GET_OUT_OF_HERE,
    NIB_LETS_HIT_THE_TRAIL,
    BRUGG_LETS_HIT_THE_TRAIL,
    NIB_LETS_BE_UNDERWAY,
    BRUGG_LETS_BE_UNDERWAY,
    VELLUM_LETS_BE_UNDERWAY,
    NIB_THIS_PLACE_REEKS_OF_DEATH,
    BRUGG_THIS_PLACE_REEKS_OF_DEATH,
    VELLUM_THIS_PLACE_REEKS_OF_DEATH,
    NIB_WHAT_DARK_DEALINGS,
    BRUGG_WHAT_DARK_DEALINGS,
    VELLUM_WHAT_DARK_DEALINGS,
    NIB_LOOK_OUT,
    BRUGG_LOOK_OUT,
    VELLUM_LOOK_OUT,
    VELLUM_LIGHT_WILL_SCOUR,
    NIB_THIS_THING_LOOKS_INTERESTING,
    BRUGG_THIS_THING_LOOKS_INTERESTING,
    VELLUM_THIS_THING_LOOKS_INTERESTING,

    // ═══ Tavern / Idle Expansion ═════════════════════════════════════════
    NIB_IS_THAT_ROAST,
    BRUGG_IS_THAT_ROAST,
    VELLUM_IS_THAT_ROAST,
    NIB_YOUVE_GOT_TO_TRY_ROAST,
    BRUGG_YOUVE_GOT_TO_TRY_ROAST,
    VELLUM_YOUVE_GOT_TO_TRY_ROAST,
    NIB_I_NEEDED_THAT,
    BRUGG_I_NEEDED_THAT,
    VELLUM_I_NEEDED_THAT,
    NIB_THATS_NOTHING_ALE_WONT_FIX,
    BRUGG_THATS_NOTHING_ALE_WONT_FIX,
    VELLUM_THATS_NOTHING_ALE_WONT_FIX,
    NIB_GREETINGS_FRIEND,
    BRUGG_GREETINGS_FRIEND,
    VELLUM_GREETINGS_STRANGER,
    NIB_WHAT_NEWS,
    BRUGG_WHAT_NEWS,
    VELLUM_WHAT_NEWS,
    NIB_WHERES_THE_PRIVVY,
    BRUGG_WHERES_THE_PRIVVY,
    VELLUM_WHERES_THE_NEAREST_INN
}
